"""add bug_name and configuration columns

Revision ID: 90d9113e2475
Revises: f8410d6dce95
Create Date: 2026-03-18 17:16:01.848873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d9113e2475'
down_revision = 'f8410d6dce95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workgroup_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('workgroup_assignments_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('workgroup_assignments_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['Employee_ID'], ['ID'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Workgroup_Schema', ['Workgroup_ID'], ['ID'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workgroup_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workgroup_assignments_ibfk_2'), 'users', ['Employee_ID'], ['ID'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('workgroup_assignments_ibfk_1'), 'workgroup_schema', ['Workgroup_ID'], ['ID'], ondelete='CASCADE')

    # ### end Alembic commands ###
